---
apiVersion: v1
data:
  ansible-conf: {{ .Files.Get .Values.ansible_conf | b64enc }}
  fe-environment: {{ .Files.Get .Values.environment_file | b64enc }}
kind: Secret
metadata:
  name: secret-{{ template "sitefe.truncname" . }}
  namespace: {{ .Values.namespace }}
