{{- if .Values.sshkeys }}
apiVersion: v1
kind: Secret
metadata:
  name: sshkey-{{ template "sitefe.truncname" . }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $path := .Values.sshkeys }}
  {{ $key }}: {{ $.Files.Get $path | b64enc }}
{{- end }}
{{- end }}
