{{- if .Values.sshkeys }}
apiVersion: v1
kind: Secret
metadata:
  name: sshkey-{{ template "sitefe.truncname" . }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $val := .Values.sshkeys }}
  {{ $key }}: {{ $val }}
{{- end }}
{{- end }}
